import os

import pandas as pd


def categorize_response(response):
    # TODO: add plurals to words
    categories = {
        "None": ["safe", "safety", "nothing", "no hazards", "no risks", "none", "hazard"],
        "Access": ["access", "clear", "access", "routes", "route", "entry", "exit", "pathway", "way in and out",
                   "obstacles", "obstacle", "door"],
        "Walk path": ["walk path", "pedestrian", "path is clear", "pathway", "walkways", "walkway"],
        "Material storage": ["materials", "storage", "work area is secure", "cargo tying test"],
        "Barricades": ["barricades", "yellow rope", "red", "red rope", "red ropes", "barricading", "fence", "fencing",
                       "signage",
                       "signs"],
        "Housekeeping": ["clean", "house keeping", "tidy", "neat and tidy", "tidy up", "put everything back in place",
                         "work area is disabled",
                         "remove everything on the area",
                         "organizing",
                         "cleanliness", "organized", "t00ls", "order", "mess", "trash", "housekeeping",
                         "hygiene"],
        "Fall hazard": ["fall", "height", "falling", "trip hazard", "tied off", "anchor point", "life line",
                        "life lines", "leading edge", "edge"],
        "Falling object hazard": ["falling object", "overhead", "above me", "working above", "work above"],
        "Heat illness prevention": ["heat", "drink", "hyrdate", "water", "shade", "temperature", "breaks"],
        "Live electrical": ["live electrical", "LOTO", "electrical", "panel", "energized"],
        "Temp electrical": ["temporary electrical", "extension cords", "extension cord"],
        "Equipment operations nearby": ["equipment", "tools", "lift", "cranes", "hoisting"],
        "Hole": ["hole", "openings", "trench", "floor opening"],
        "Other contractors working nearby": ["other contractors", "crew", "crews", "others", "other teams",
                                             "other companies",
                                             "contractors nearby", "contractors", "people", "other trades"],
        "Material not secured": ["unsecured", "loose", "not secured"],
        "Struck by hazard": ["struck by", "hit", "securing cargo", "securing material"],
        "Hoisting activities nearby": ["hoisting", "crane", "lifting", "hook", "rigging", "overhead loads"],
        "Slip, trip, fall hazard": ["slip", "trip", "fall hazard", "tripping", "wet surfaces", "stumble"],
        "Confined Space": ["confined space", "tank", "vessel", "hole watch", "dregeur", "sniffer"],
        "Installed systems": ["systems", "piping", "installed", "install", "protect"],
        "Pressurized system": ["pressurized system"],
        "Combustibles": ["combustibles", "half an hour", "fire watch", "wait", "30 minutes", "flammable", "fire",
                         "hot work", "flames", "spark", "sparks",
                         "flame"],
        "Sharp edges": ["sharp", "cut"],
        "Excavation hazards": ["excavation", "trench", "digging", "collapse", "cave in", "shoring"],
        "Impalement hazard": ["impalement", "sharp object", "impale", "stab", "cut"],
        "lighting": ["lighting", "adequate light"],
        "Trade damage": ["trade damage", "damage", "damage in area"],
        "Line of fire": ["line of fire", "to hands", "to hand", "lof"],
        "Traffic": ["traffic"],
        "Scaffold issues": ["scaffold"],
        "Congestion": ["congestion", "crowded", "narrow"],
        "Weather": ["weather"],
        "Gas cylinder": ["gas cylinder", "oxygen", "acetylene", "argon", "propane"],
        "Ladder condition": ["ladder"],
        "Road conditions": ["road conditions", "for a truck"],
        "Live system": ["live system"],
        "Pinch points": ["pinch points", "not being between two points"],
        "Inspections": ["inspections", "checking tools", "checking equipment"],
        "Dust": ["dust"],
        "Underground system": ["underground system"],
        "Emission hazard": ["emission hazard"],
        "Chemical hazard": ["chemical hazard"],
        "Changes": ["change", "changes", "evolving", "changing"],
        "Hazards": ["hazard", "hazards", "danger", "dangers", "risks", "risk"]
    }

    response_lower = response.lower()
    matched_categories = set()

    for category, keywords in categories.items():
        for keyword in keywords:
            if keyword in response_lower:
                matched_categories.add(category)

    # If no category matches, default to "None"
    if not matched_categories:
        matched_categories.add("None")
    elif "None" in matched_categories and len(matched_categories) > 1:
        matched_categories.remove("None")

    return ", ".join(matched_categories)


# TODO: Grab values from pre-existing table to populate list
responsesCopied = [
    ## QUESTION 3 BEGINS HERE
    "I reported the blockout to job services and they came and closed it. Until they closed it I placed a hard red barricade around it",
    "Stay away from hazards if possible and plan safe work",
    "Personal protective equipment",
    "Arranging the equipment in the cabinets, cleaning the work area and removing fencing",
    "Make sure the area is clean.",
    "Cleanliness, order and forward planning",
    "work carefully work according to the work plan",
    "Before I finish the work day I tidy up and clean if there is a danger I close the work area with shiloh",
    "Planning a return path and cleaning the area",
    "Check list for departure",
    "keep the area clean",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "You put everything back in place",
    "I'm house keeping and good store material in the work area every time before leaving a work place, No hot work delay period.",
    "Orderly work and according to the law",
    "Work according to a plan",
    "Don't rush, think before every step, work according to safety guidelines",
    "Mapping the risks and explaining and emphasizing them to the employees",
    "Entrance/exit access road",
    "Cleaning at the end of the day with a yellow ball on remaining parts",
    "work safely",
    "walking on free paths",
    "You can always try as much as possible, but there are unexpected things",
    "maintaining safety",
    "work safely and carefully",
    "Entrance/exit access road",
    "Everyone cleans the work area with personal protective equipment",
    "walking on free paths",
    "walking on free paths",
    "Walk for them built",
    "Remove any obstacle, collect tools",
    "Cleanliness, order and organization",
    "If I find hazards, I will call the attention of everyone involved and, if necessary, I will stop work",
    "Fencing the work area with red rope using the appropriate equipment",
    "Maintaining a fenced area and a safety zone and passing on information to those in charge",
    "work safely and explain to employees how to work safely identify hazards and deal with them Training for employees every morning",
    "Look for any safety hazards",
    "Look for any safety hazards",
    "Look for any hazards",
    "Planning a return path and cleaning the area",
    "- reinstall hole covers, put hard barricades back up instead of red rope",
    "Staff self-examination",
    "A clean and modeled work area, fencing adapted to the area according to risks. Access roads are clear of disturbances. The contractor's equipment is clean and organized in designated boxes.",
    "walking on free paths",
    "Always clean your area during all the work day special before I leave the site p",
    "Use of protective equipment",
    "Staff self-examination",
    "Observe the safety instructions, order and cleanliness and understand the work'",
    "Make sure to drink in a clean area",
    "Ensure access ways at the beginning of the work and thorough planning from the beginning of the task until the end",
    "Securing tools, working with a harness at height, does not enter an area that is dangerous for me",
    "Order and cleanliness at the end of the day",
    "doing hose kiping end of day",
    "When we work at clean area",
    "Safe fencing and clear signage",
    "End of work day 30 minutes before inspection of cleanliness and order area!",
    "We will make sure to convey the work plan to the entire team and ensure that the work area remains clean and that there is communication between the entire team",
    "A work stop is carried out to make sure that there is no safety hazard in the mash area",
    "We need a spotter not attached to the daily work.",
    "Team leader + EHS person check and remove everything on the area.",
    "Cleaning and arrangement when I'm done, yellow robe in storage area",
    "Housekeeping, organize the materials, no trash on the floor, all electrical and motorized equipment are closed or in there box.",
    "Lower red ropes and make sure that nothing remains on the steel beams and could fall down",
    "We will keep a work area free of people inside the red line",
    "Lowers red ropes and parks the platform when it is closed",
    "ladders",
    "Close the crane and make sure the area is clear",
    "Performs a scan of the work area and cleans the area",
    "Areas should be clean and clear, barricades should be removed after the job is done.",
    "Take the necessary steps and work according to the mission planning and ask the employees to be alert for changes",
    "Do a walk down to be sure red rope and tools are removed properly. Try to make it look like they were never there",
    "We will keep a work area free of people inside the red line",
    "We will keep a work area free of people inside the red line",
    "Make sure all our tools and materials are secured and tied off and the work area is secured",
    "Make sure that you create with personal protective equipment and secure equipment that won't fall off the roof",
    "Careful work and ppe",
    "Making sure I didn't leave things open-ended",
    "Confirmation that the work equipment has returned to its place, and the work area has been cleaned in preparation for tomorrow's work",
    "Arranging all the accessories and checking them, the crane is properly folded so that it will not be a hazard to nearby pedestrians",
    "work calmly and carefully",
    "We will make sure that nothing is forgotten, neither materials nor tools",
    "Work carefully",
    "Spotters that incurred all the area stays clean during all the work day.",
    "Careful work",
    "I make sure that the team will perform non-reckless safety actions and will be focused.. use of proper equipment and use of personal protective equipment",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "Before leaving, check that everything is connected and check the equipment",
    "Planning a return path and cleaning the area",
    "Planning a return path and cleaning the area",
    "Scan and clean to avoid obstacles and dangers",
    "1. Remove all the debris from the work area. All the electrical tools are disconnected from the power source. All the materials storage area is yellow fencing and signed",
    "Uses hedges and viewer",
    "Walk paths always clear, material stacked and organized manner",
    "Planning a return path and cleaning the area",
    "When I observe the safety rules I guarantee our safety",
    "Proper fencing with correct signs",
    "Order and cleaning during the day CLEAN AS YOU GO",
    "I will make sure to work according to all the instructions",
    "Picking up all the work equipment from the floor... closing the openings we created. Cleans residual dirt.",
    "Proper cleaning and fencing order according to the danger.",
    "Entry/Exit access",
    "Maintain safety rules f",
    "I make sure that the workers have finished the work, for their observation the order and cleanliness of the workplaces, not to leave them pits without a fence, and without signage, if they observe the daily safety instructions, etc.",
    "Clean up after work",
    "Order and cleanliness always",
    ", covering systems and while working at a tying height 100% above the head",
    "Yes",
    "Clean the work area, remove the red rope when there is no danger to life",
    "Yes",
    "Yes",
    "We will keep a work area free of people inside the red line",
    "Before I finish the work day I tidy up and clean if there is a danger I close the work area with shiloh",
    "Cleaning area, take down any red rope, move equipment so it is not blocking others work",
    "We will work according to the task requirement with the appropriate equipment for the job",
    "Work according to safety rules and build a work plan before starting",
    "order and cleanliness",
    "A clean, tidy, fenced place",
    "housekeeping",
    "Work carefully, while maintaining the rules and procedures + maintaining proper work logic, not trying too hard to work according to the training and instructions we received from the first day at work",
    "Work according to the rules",
    "Follow the safety instructions",
    "Bankin's order in the fence for equipment",
    "1. Remove all the debris from the work area. 2. All the electrical tools are disconnected from the power source. 3. All the materials storage area is yellow fencing and signed",
    "Yes",
    "Yes",
    "Remove power cords and other equipment from scaffold and use yellow rope to mark stored materials",
    "Rope closure as required. Fencing power cut hazards",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "INFORM OUR CREW 30 MINUTES BEFORE STOP WORK, GOOD HOUSEKEEPING WORK AREA AND PARK EQUIPMENT SIDE OFF WALK AREA AND CHARGE EQUIPMENT FOR TOMORROW WORK.",
    "Yes",
    "Make sure everything is secure and safe",
    "I, the observer, accompany the forklift all the time, checking the lashing of cargo, keeping people away",
    "do good housekeeping, and if necessary barricading and putting warning signs",
    "leaving an orderly passage free of obstacles",
    "Cleaning the work area and removing hazards",
    "Careful work, use of protective equipment",
    "Leave a clean, tidy place, with a yellow fence with proper signage",
    "adhere to safety procedures,",
    "Vigilance, attention, advance planning of the work and the stages of the work",
    "Makes sure that the work area is clean and tidy, that the stage is in good condition without leaks, that the diapers are intact and clean, removes a red rope that is not in danger of life",
    "I will think about how I minimize the risk",
    "Tie the pipe at the end of the work day, tidy up",
    "Behave according to the rules of the place. Clean environment. Removal of red rope. There is no danger to life for those who come to the work area",
    "Reference to hazards and dangers in the preliminary work planning",
    "Order, cleaning, folding tools, closing a fence",
    "Daily inspection of each employee for personal protective equipment and replacement of non-standard equipment",
    "We will follow the rules and order and cleanliness",
    "Collecting equipment and obstacles. and the hoskiping",
    "We will make sure to rest and understand the work",
    "During the day and at the end of the day, the work area is cleaned, the red rope is removed when there is no danger to the lives of those who come to my work area",
    "Work according to the procedures and fitipi",
    "Takes care to fence off the workplace and blocks or keeps victims away",
    "Collect the equipment of the cabinets, secure boards",
    "Work according to the laws and rules accompanied by a safety officer",
    "Everything is in order inside the barricaded zone",
    "remove barriers and store materials. housekeeping",
    "Plans and organizes a work environment, leaves a clean and tidy work area without debris, fences off the storage area with yellow tape",
    "1. Remove all the debris from the work area. 2. All the electrical tools are disconnected from the power source. 3. All the materials storage area is yellow fencing and signed",
    "Make sure nothing left at heights. Housekeeping",
    "A fenced work area with signs and an exit hatch",
    "The work environment is free of obstacles",
    "By checking that the work area is secure 10 minutes before quitting time m",
    "They leave a clean and tidy work area",
    "Cleaning at the end of the day, without obstacles",
    "We will work in an orderly manner, we will remove any obstacle that will disturb us, we will work according to a work plan and PTP",
    "With the help of appropriate fencing and an entrance and exit gate",
    "Set up another walkway without hazards",
    "Careful work and ppe",
    "Do a scan and make sure the area is clear of hazards",
    "Do a risk assessment and fill in the ptp tied at the height of the gender opening cover",
    "observation",
    "The equipment is arranged, cleaned and fenced according to the hazards/procedures",
    "I will remove everything from the work surface",
    "1. cleaning all areas and all work that we have done. 2. all electrical equipment remove from energy 3. store all our tools in the Official storage area 4. make sure not to leave materials lose on heights or leave any equipment on heights 5. anything that is removed of course by permission must be back as it was at the end. 6. ensuring that Argon panels are fully closed 7. all cylindrical Argon balloons must be capped. 8. general housekeeping",
    "Assessment of the entire work area including those who work in my environment",
    "Correct use of personal protective equipment. Knowing the task, proper planning and the risks",
    "Make sure I got all the impalement protection in the area, the area is supposed to be clean and clear of debris and left behind so there won't be no trip hazard.",
    "I clean the area before leaving",
    "Last 15 minutes is for cleanup",
    "Fold tools, electrical cables, cleaning, close fence",
    "Fold tools, electrical cables, cleaning, close fence",
    "Drink a lot and pay attention to the workers around you",
    "Attention",
    "Do not sing tools on the tarsal",
    "Good housekeeping",
    "We will tidy up, clean, put everything back in place, put a yellow rope around it",
    "Works according to the procedures and takes care of a clean work area at the end of the work day",
    "Housekeeping",
    "Convention against unnecessary risks",
    "Work carefully according to safety rules",
    "Maintain order and cleanliness",
    "Leave a clear and orderly passage from obstacles",
    "We will tidy up the work area at the end of the day and maintain proper fencing and signs",
    "Walk paths always clear, material stacked and organized manner",
    "Planning a return path and cleaning the area",
    "Cleaning and checking equipment",
    "Before starting work and after finishing work, I will clean and organize the workplace and storage",
    "Maintain a clean and tidy work area at all times",
    "to have proper control measures in place persons should wear proper PPE",
    "work according to the instructions",
    "Clean, take down red ropes, good communication between trades, clients",
    "Clean my area and take down the barriers case....",
    "Order, cleaning, folding tools, closing a fence",
    "We will keep a work area free of people inside the red line",
    "Slaves according to a work plan we decided together",
    "follow the safety rules, think twice before you act",
    "Cleaning, arranging tools, fencing if needed and tying things that won't fly away due to weather",
    "A clear approach",
    "Good housekeeping",
    "Cleanliness and order in the buffet today, there is a lack of tools for the cabinet disconnecting from electricity everything that is dangerous for the trash can",
    "Double check that properly arranged and with proper barrier",
    "Work according to a work plan",
    "Order and cleanliness at the end of the work day",
    "when shift end do proper housekeeping. all mechanical equipment park sufficient palace and must be switched off, all tools keep in boxes.",
    "I leave everything clean and organized.",
    "Safety first",
    "1. Housekeeping 2. Put back all electrical equipment and leave un-energized 3.",
    "Identification of all amounts and appropriate controls",
    "By checking that the work area is secure 10 minutes before quitting time m",
    "We work according to a work plan that we set",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "Work carefully",
    "Work carefully",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "I will reduce risks and hazards",
    "My team is working with rebar so it is very important to keep all the sharp edges covered to avoid injuries, a safe access point or walk path through the area must be provided and clean of debris or materials left behind. Also the materials themselves should be stacked properly and not to lay on the ground.",
    "Proper storage of the ladder after the work is finished",
    "Planning a return path and cleaning the area",
    "Work according to a PTP that is correctly and completely registered",
    "Order and cleanliness at the end of the work",
    "To guide the employees before each working day",
    "Set up another walkway without hazards",
    "Before leaving work switch off all equipment and remove all barricades, keep all tools in box, end off day maintain housekeeping.",
    "Clean the area and remove Red rope",
    "By doing a safety assessment 10 minutes before leaving",
    "Order and cleanliness",
    "Scan the work area before leaving and the workplace is clean and tidy",
    "I need to house keep my work area",
    "Make sure everything is in order",
    "Fencing the work area",
    "We will keep a work area free of people inside the red line",
    "Work according to a work plan",
    "Work according to a work plan",
    "I clean my workplace and put all the materials on the cart, and when I leave the workplace I go wherever I am allowed to go",
    "Fencing a storage area and working order and cleaning",
    "A clean work environment and a tidy storage area and to know all the risks in the work area",
    "A work stoppage is carried out to make sure that there is no safety hazard in the thick area",
    "Use of personal protective equipment, careful work",
    "Clean up before starting work and fence off an area and make sure to clean at the end of the work day",
    "It is forbidden to touch the systems around us without permission",
    "Works according to safety procedures and cleanliness of the work area",
    "order and cleanliness",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "Planning a return path and cleaning the area",
    "Tool and materials search tour",
    "Do not touch physically or with the lifting platform in the electrical network",
    "Good housekeeping",
    "im looking for the nearest rest shelter and drink station,",
    "Avoids risks and hazards",
    "net",
    "Good housekeeping / close area off with yellow / red rope if there are any hazards",
    "to work with ppe to understand what ribek tzeh i do",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "By doing a safety check 10 minutes before departure",
    "First ensure the work area, leaving before good housekeeping and power supply disconnected, and material and tools need to be secured.",
    "First ensure the work area, leaving before good housekeeping and power supply disconnected, and material and tools need to be secured.",
    "I will avoid unnecessary risks and hazards",
    "In the morning I will plan the work during the day so that I always have safe access to get in and out",
    "Clean the work area, remove red and yellow waste that you no longer need",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "Planning a return path and cleaning the area",
    "Inspection in place",
    "By doing a safety check 10 minutes before quitting time",
    "Area review",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "check the work environment of our neighboring companies.",
    "when shift end do proper housekeeping. all mechanical equipment park sufficient palace and must be switched off, all tools keep in boxes.",
    "Work according to a work plan",
    "Work according to a work plan",
    "Good housekeeping",
    "Be smart all the while and wear a proper PPE while on site",
    "control the hazard, put a land yard for a tool and put rwd rope",
    "Attention to the environment",
    "Every day checking the equipment twice",
    "What 30 minutes because of hot work",
    "Housekeeping",
    "All the materials have to be secured, barricades and fall protection, housekeeping.",
    "Clean the work area for the next day",
    "We will keep a work area free of people inside the red line",
    "Use of personal protective equipment and careful work",
    "Removes waste, works at height with a proper harness and ladder",
    "Lowering surfaces to floor level or very low",
    "Leave a tidy area free of interfering equipment and suitable fencing. In addition, check if there are no obstacles left that might interfere with other contractors",
    "Makes sure everything is fixed and secure. Leaves fencing as needed. Cleaner",
    "drink a lot of full ppe",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "Work according to a work plan",
    "Yes",
    "work safely according to the procedures",
    "A tour of work stations around",
    "Always wear a proper PPE while on site and proper housekeeping",
    "Carrying out cleaning and order in the work area and removing a red rope that is not dangerous",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "Works according to existing work procedures and in accordance with the law",
    "yes",
    "Yes",
    "Staying alert, ptp before starting work",
    "Careful work",
    "Fence the workplace",
    "A lot of religiousness, order and cleanliness at the end of a working day, work safely and not recklessly, secure tools",
    "Make sure that there is no object left in a place it is not intended for",
    "when shift end do proper housekeeping. all mechanical equipment park sufficient palace and must be switched off, all tools keep in boxes.",
    "Careful work",
    "A safe exit is by closing the work area, collecting equipment, cleaning, collecting fencing, storing equipment and materials in a safe manner that does not interfere with continuous work, marking and marking equipment, loading the lifting platforms at a less accessible point, notifying the foreman and supervisor of closing the work day.",
    "Area review",
    "Take care of masks for all the staff",
    "We will use all the tools we have to protect ourselves",
    "Work planning at the beginning of the day, organization of the equipment hole and dogs, cleaning of the work area",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "Cleaning",
    "Access check",
    "Fencing work area before starting work",
    "clean, and fencing removed at the end of the work",
    "Do not cross red and yellow fencing. Do not pass under the raised equipment.",
    "Work according to safety procedures",
    "Fencing the work area before starting work, bringing appropriate equipment",
    "work safely and explain to employees how to work safely identify hazards and deal with them Training for employees every morning",
    "Please note that the entire work area is disabled before we leave",
    "Clean the area",
    "Keep the workplace tidy and free of obstacles. Removal of fencing that may interfere with night work. Electric tools are disconnected from the power supply and must be plugged in according to the work area.",
    "Have multiple people check the area several times to be properly cleaned up and tidied",
    "cleanliness and order",
    "Red rope security cleaning order",
    "Organize, clean, remove unnecessary ropes",
    "Household",
    "cleans up after Checks the work and that there are no hazards left",
    "cleans up after Checks the work and that there are no hazards left",
    "Work according to safety procedures, refining procedures",
    "Fencing work area before starting work + cleaning",
    "Machinery disabled, barricades removed, housekeeping",
    "A responsible inspection, to check that tools are in order, and there is no hazard for the next day",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "Cleaning checks if everything is reinforced with blocks that we assembled",
    "work safely and explain to employees how to work safely identify hazards and deal with them Training for employees every morning",
    "Arrange and take the equipment and clean",
    "In the relationship, consult with the viewer all the time and the area will be neat and clean and if there is a fence that needs to be pulled to the sea, otherwise they will say in the comments",
    "Clean the area and close any loose ends",
    "Cleaning the area, making sure no tools are left",
    "Employees before the work agenda 6 Maintaining procedures",
    "cleans up after Checks that there is no garbage or tools left, lowers a red rope",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "cleanliness and order",
    "Order and cleanliness throughout the area",
    "Use red rope. Use safety rules",
    "Cleaning and organizing the work space",
    "That the area is clean and orderly without any obstacles and the handing over of the master/yellow fencing",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "We check that we disconnect everything from the electricity, clean after ourselves",
    "Organize, order material and cleaning",
    "Cleaning after ourselves. And not leaving anything on the floor",
    "Make sure to take all day, work tools, and leave it clean",
    "Housekeeping / clean as you go",
    "Removal of all garbage and removal of fencing from the work area. Only a very limited storage area remains at the end of the work day because different contractors work here at night",
    "Field tour during the day",
    "Checking that there are no casualties",
    "Do the cleaning order, removal of ropes at the end of the day and a final round for final inspection",
    "I keep my work area clean and tidy",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "Walking on the lines",
    "We will work according to a work plan in which the various risks that exist during the work are evaluated",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "Fact according to work plan",
    "Fact according to work plan",
    "Fold all the equipment, clean and organize the work area, throw away the garbage, remove cables and obstacles",
    "Yes",
    "Wait in the area for 30 minutes and check everything",
    "Employee training, proper protective equipment, proper work tools",
    "Define the work area",
    "Stop before and spend time in order and cleanliness",
    "Works according to procedures",
    "work according to procedures",
    "Using the proper equipment & tools. Working according to the plan. If I see something I notify my EHS or foreman",
    "Observe safety instructions and use personal protective equipment",
    "Everything ended well in all respects, the condition of the area, materials in a defined place, if necessary, does not pose a danger to other people, and to leave Rosh Seret, aim to improve the working area",
    "Check everything before we go",
    "Yes",
    "Employee trainings, and creating a mutual relationship between the employees and the supervisor",
    "Field tour during the day",
    "Checking that all the equipment is in a safely secured place",
    "Full PPE, full fencing and full tying",
    "Eliminate all hazards and do the Oskipig and report to Hoffman if there are any dangers at night",
    "make order and cleaning",
    "Make a tollbox in the morning before starting work and take care of every safety thing",
    "Platforms are returned and fences are cut",
    "Neat and clean",
    "Neat and clean",
    "Blow the zone whistle and tidy up the zone before leaving",
    "tidy up before leaving",
    "Collecting waste, returning tools to the place, tying equipment such as ladders and the like",
    "look all the time",
    "Performing work according to PTP, doing Housekeeping after work",
    "If I work according to the procedures",
    "No answer",
    "Yellow rope and stickers",
    "to heart node",
    "communication",
    "Half an hour before the end of the shift cleaning area scanning order",
    "Arranged yellow rope and fence poles to barricade",
    "work safely work slowly securing tools to plan the risks before starting the work",
    "Walk slowly and check the area around",
    "Work according to the instructions given in the morning of work",
    "Work carefully and leave slowly because some workers have finished their work",
    "Securing tools and fencing off the work area and placing a watcher to keep people away",
    "Order and clean the work area",
    "Do cleaning and disconnect cables from electricity if there is ongoing work to fence the area",
    "Staff self-examination",
    "Recycle everything and put the stage in loading",
    "All the time we go, the observer will assess the risks throughout the entire working time",
    "neat and tidy",
    "The observer will continuously check the work area and the risks that exist",
    "Order, cleaning, folding tools, closing a fence",
    "Housekeeping the work area",
    "I will follow the instructions I received from my manager",
    "Work according to the safety rules on the site",
    "To behave according to the safety rules on the site towards and towards the employees with me",
    "Stay away from the risk area and walk slowly to maintain safety",
    "arrange while and at the end look around",
    "Risk assessment training and site preparation",
    "Before starting work and after finishing work, I will clean and organize the workplace and storage",
    "Order and cleanliness of the work area during the day and at the end of the day",
    "After us, we use personal protective equipment",
    "work safely and explain to employees how to work safely identify hazards and deal with them Training for employees every morning",
    "Employee training, attention, teamwork.",
    "Call another team member",
    "Clear the area first and cover the sharp object before starting the work and good housekeeping",
    "Working with a close observer. Cargo tying test",
    "Makes sure the area is clean and tidy and ties and secures any element that may fall",
    "Pay attention to things",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "Work according to the procedures and rules of the place",
    "Making sure that the team members know the task, everyone has personal protective equipment, arranging the work station and folding all the equipment and putting it in the equipment cabinet",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "Wait in the area for 30 minutes and check everything",
    "We will follow the rules and work carefully with a viewer",
    "As a team we will make sure that everything is in order and there are no hazards for our safety and the safety of others",
    "We stop hot work 30 minutes before finishing work, and we clean our work area.",
    "Order and cleanliness, work planning",
    "Red fencing to the swing area and a spectator",
    "Task planning even at the end of the day",
    "Evacuation of free access area",
    "Scan the work area before leaving and the workplace is clean and tidy",
    "order and cleanliness",
    "Vigilance to the environment that goes",
    "Employee training, safety cooperation.",
    "Make sure that we turn off all the electrical tools and make sure that we clean our area",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "After a general inspection",
    "Housekeeping checking everything clean",
    "Housekeeping checking everything clean",
    "Clean the work area, take down red and yellow ropes that you no longer need",
    "Mark to fence sharing",
    "Personal responsibility and concern for safety",
    "Work according to procedures",
    "Tour before the end of the day - order and cleanliness",
    "that there is no one working on the stage",
    "housekeeping",
    "order and cleanliness",
    "Return equipment, clean work area",
    "Training employees for safe work",
    "Clean environment, employee training",
    "Order and cleanliness of the area",
    "housekeeping",
    "Work area order",
    "Platforms are returned and fences are cut",
    "Fencing joints leave a clean area and equipment is locked in the cart and equipment is not left high on the construction",
    "Everything is clean and we didn't forget anything on the floor",
    "that we arrange and clean the area where we worked",
    "all hot work are cold and closed. with proper housekeeping",
    "Employee trainings, and creating a mutual relationship between the employees and the supervisor",
    "return stage to storage",
    "move the stage and the equipment collection to the warehouse",
    "Work according to the enclosed space procedure",
    "Half an hour ago, work was being created, checking the area, cleaning, fencing, signs",
    "move the stage and the equipment collection to the warehouse",
    "move the stage and the equipment collection to the warehouse",
    "job location ensures any times work there on other company",
    "order and organization and cleanliness",
    "Be alert to all dangers and not hinder safety in the field",
    "House keeping",
    "House keeping",
    "Planning a return path and cleaning the area",
    "Stay away from the risk and electrical panel",
    "when shift end do proper housekeeping. all mechanical equipment park sufficient palace and must be switched off, all tools keep in boxes.",
    "Scan to identify hazards.  Order and cleanliness",
    "Careful work",
    "Clean environment, employee training, fencing and marking of hazards and tools.",
    "Conduct a tbt to team, explain what we can do. Avoid touching cables and electrical panels, secure yourself and be aware",
    "A shot of the area before the job is done",
    "remove ropes, all t00ls are stored in a safe place",
    "They update the foreman, fence after us, use personal protective equipment",
    "Clean and the equipment checked and stored in the right place",
    "Leave the workplace clean and tidy",
    "Walk paths always clear, material stacked and organized manner, clean as you go threw the day",
    "Full personal protective equipment, PTP training, checking the essence and the work area and refilling",
    "All equipment meets the standard and leaves the workplace as I received it",
    "Order and cleanliness in the work area all the time and at the end of the day",
    "Wait 30 minutes to see that nothing has sat on fire",
    "work according to plan",
    "Housekeeping",
    "Cleaning, folding electric cable, tools, closing fence",
    "order and cleanliness",
    "Work according to procedure",
    "He has no answer",
    "He has no answer",
    "Clean the area from falling materials",
    "Clear the area of ​​materials and equipment that can fall",
    "Work well, work for sure",
    "Employee training, cooperation, elimination of hazards, fencing and equipment marking",
    "By leaving the work area clean and tidy",
    "Tidying up the place all the time, it's a pity with signage on the premises work",
    "Equipment arranged in the area",
    "Checking the cleanliness of the work environment Checking the current work plan suitable for the task Defining a storage area for raw materials Defining walking routes",
    "Be all the time with eye contact and also go out carefully slowly",
    "30 minutes before the end of work time, we will stop hot work and clean and inspect the area always before leaving work.",
    "Order, cleaning, fencing",
    "Ehuda is careful and safe",
    "Clear clutter, store tools properly, secure equipment, check lighting, report issues.",
    "Ehuda is careful and safe",
    "Stay away and watch the trucks",
    "Clear clutter, store tools, secure equipment, check lighting, report issues.",
    "Remove hazards, double-check safety equipment, lock hazardous materials, tidy up.",
    "I will arrive at the site before starting the work and check what could cause the danger",
    "Maintaining order and cleanliness",
    "Stopping work in a situation of danger, identifying risks and maintaining a clean work environment",
    "Check the equipment for order and cleanliness in the area",
    "Work according to a work plan",
    "Take care to look for dangers",
    "order and cleanliness",
    "Tool storage",
    "act safely and perform safe operations according to the ptp work plan",
    "Order and cleanliness at the end of the shift, bringing all tools and work equipment to the designated area",
    "Before leaving I told me to clean our area",
    "Look before and check that everything is in order",
    "Make sure no one is in the elevator",
    "leaves behind order and cleaning and folds equipment into boxes",
    "At the end of the work collect the equipment",
    "Return the equipment to the place",
    "cleanliness",
    "Arrange",
    "cleanliness",
    "looking",
    "Everything is clean",
    "Distinction on the environment",
    "Make sure the whole area is clean and tidy and all the equipment is in place",
    "Make sure the equipment is in place and there are no things that could cause damage",
    "look at the environment",
    "I will confirm with the safety supervisor that the power is fine and everything is clean and tidy and I will leave the site",
    "order and organization",
    "examination",
    "I will make sure there is no danger of hot work",
    "arrange and organize",
    "Talk to the staff and check with all the help for a clean job",
    "Make sure that we check all the area and all the hazards before we leave",
    "Scan the work area before leaving and the workplace is clean and tidy",
    "Ordering and cleaning operation. Preparing equipment for the place",
    "order and cleanliness",
    "Keeping the area clean, inspecting our electrical tools, proper storage of equipment.",
    "Order and cleanliness, employee training, safety talk in the morning, raising awareness of risks",
    "Careful work",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "work according to plan",
    "Tidying up the area and returning equipment to the cabinets and screws to the bucket",
    "To observe all the rules and open matters and maintain communication",
    "Encumber a fence on a viewer",
    "Work carefully, work slowly, work in an insurance way, sharpen tools",
    "Be sure to have a fence attached to a proper fence",
    "Do not approve tools at the end of the day or material",
    "Fold clean area equipment",
    "Fencing and cleaning",
    "defined and clean",
    "Fence the area and do not allow casualties",
    "Housekeeping",
    "To drink water.  Not being in blind areas.  Watchman",
    "Use personal protective equipment to work according to a work plan, to order and clean the work area",
    "Tidy and clean",
    "Proper housekeeping,",
    "Unpack the puppies and clean the area",
    "We will use skilled people and provide them with the necessary equipment",
    "Close the site, lock it, work according to the requirements",
    "We will avoid the risk we have identified as much as possible",
    "Cleaning, turning off the electricity, folding tools,",
    "Arranging the carts of the material in a safe place without disturbing one app with fencing",
    "Identify the dangers and work according to the safety instructions",
    "We will identify all the risks and dangers we have at the beginning of the work",
    "Not being between two parts.  Watchman",
    "Not being between two parts.  .fanc.  PPE. Harrnst",
    "Employee training, cooperation",
    "Cleaning, closing a fence",
    "Before starting, we made a tollbox near the work area because there was a change in the team",
    "Order and cleanliness, storage area fencing and a hazard-free work environment",
    "According to the results of the survey, risks and what is required of me and working for hours",
    "Before leaving, check that everything is connected and check the equipment",
    "Return equipment, clean work area",
    "Return equipment, clean work area",
    "Order and cleanliness of the area",
    "Return the hedges and make order",
    "Sing the work area tidy",
    "Before leaving, check that everything is connected and check the equipment",
    "We will write down a mission plan. Advance and work safely",
    "Arranging tools to their place",
    "Cleaning, folding electric cable, tools, closing fence",
    "Cleaner",
    "arrange the equipment",
    "Careful work",
    "Field tour and inspection with contractors",
    "Order and cleanliness at the end of the day",
    "Clean the work area, put tools in place, do not leave objects that people can get hurt",
    "Order and cleanliness",
    "Choose a safe way",
    "Terminate the capacitors at a safe height",
    "Arranging all the tools in their place",
    "Keeping work area clean. Never be in a hurry. Using proper walking paths.",
    "If there are no dangers dismantle the fences and be alert to all parties",
    "Work according to a work plan",
    "I am careful and take care of myself and the people who work with me",
    "Make order and cleanliness in the work area",
    "Make order and cleanliness in the work area",
    "Evacuate all equipment",
    "Clear the fences and tidy up the whole area",
    "Pay attention to the whole area",
    "to organise",
    "Follow the safety procedures, personal protective equipment",
    "Leave work with a good state of mind",
    "Stop hot work half an hour ago",
    "Make sure tools are returned to their place.",
    "perform a final scan of the area.",
    "check that there are no objects scattered on the floor.",
    "Make sure all signs and warnings are in place.",
    "Check that the area is free of debris.",
    "check that the cables and wires are organized and not scattered.",
    "Scan to make sure there are no leaks of hazardous materials.",
    "Mark and warn of any hazard detected during the day",
    "Check that the equipment is turned off and locked",
    "Housekeeping cleans the area and barricade working zone",
    "work according to a work plan",
    "Checks the area during the day.  to assess the hazard",
    "assess the hazard and perform controls",
    "work carefully",
    "to work orderly and safely",
    "work slowly",
    "Checks the area during the day.  to assess the hazard",
    "Scan the work area before leaving and the workplace is clean and tidy",
    "Personal protective equipment training PTP firefighting equipment",
    "Training and work plan and appropriate personal protective equipment",
    "Checking out the work area before we are gone",
    "Acknowledges that the work areas are tidy, acknowledges that the workers have finished their work safely",
    "Everyone will discover personal responsibility",
    "Folding and time for cleaning",
    "Communication between the team and filling out PTP in the field after the evaluation of the field",
    "Cleaning work area. Equipment and material handling. Equipment and material inspection",
    "Good housekeeping, use harness, put the redrope with spotter",
    "To photograph the area after finishing work",
    "Clean as it should be, clean work area",
    "to keep the bayonet",
    "I asked a foreman to take care of it, and put up a fence",
    "Order and cleanliness of the area",
    "If there are scraping tools if there are abrasive materials",
    "Waiting half an hour at the end of the day",
    "Work in a neat and orderly environment. Work according to PTP, and according to the safety rules",
    "Arrange and clean the area, arrange tools and leave the area empty",
    "Order and cleanliness of the area",
    "That the area will be regulated and fenced and after the work is finished the red fence will be dismantled",
    "Field scans",
    "Barricade and all clean",
    "Housekeeping",
    "Cable storage in the workplace must be at height and not on the floor",
    "Do not rush and follow ptp",
    "order and cleanliness",
    "Making order and cleaning in the work area and removing a red rope that does not pose a danger to the lives " +
    "of those who come to the work area",

]

dynamicallyCat_responses = [categorize_response(response) for response in responsesCopied]

downloads_folder = os.path.join(os.environ['USERPROFILE'], 'Downloads')
file_path = os.path.join(downloads_folder, 'categorizedSurveyResponsesQuestion3.xlsx')

# Creating a DataFrame for the values
df_responses_all_corrected = pd.DataFrame({
    "Response": responsesCopied,
    "Category": dynamicallyCat_responses,
})

# Generating summary of categories
category_summary = df_responses_all_corrected["Category"].str.get_dummies(sep=', ').sum().sort_values(ascending=False)

# Converting the summary to a DataFrame for better readability
category_summary_df = category_summary.reset_index()
category_summary_df.columns = ['Category', 'Count']

# Saving both DataFrames to a single CSV file with two sheets
with pd.ExcelWriter(file_path) as writer:
    df_responses_all_corrected.to_excel(writer, sheet_name="Responses", index=True)
    category_summary_df.to_excel(writer, sheet_name="Tally", index=False)
